module.exports = [
  {
    name: "Italian",
    item: [
      { name: "Pasta", url: "pasta.jpg" },
      { name: "Pizza", url: "pizza.jpg" },
      { name: "Arancini", url: "arancini.jpeg" },
      { name: "Lasagne", url: "lasagne.jpg" },
      { name: "Osso buco alla Milanese", url: "ossobuco.jpg" },
      { name: "Polenta", url: "polenta.jpg" },
      { name: "suppli", url: "suppli.jpg" },
      { name: "Bruschetta", url: "bruschetta.jpg" },
      { name: "Risotto", url: "risotto.jpg" },
      { name: "Saltimbocca", url: "saltimbocca.jpg" },
    ],
  },
  {
    name: "Beverages",
    item: [
      { name: "Tea", url: "tea.jpg" },
      { name: "Coffee", url: "coffee.jpg" },
      { name: "Fruit punch", url: "fruit-punch.jpg" },
      { name: "Soft drinks", url: "soft-drinks.jpg" },
      { name: "Buttermilk", url: "buttermilk.jpg" },
      { name: "Cold chocolate", url: "cold-coco.jpg" },
      { name: "Milk", url: "milk.jpg" },
      { name: "Wine", url: "wine.jpg" },
      { name: "Soup", url: "soup.jpg" },
      { name: "Lemonade", url: "lemonade.jpg" },
    ],
  },
  {
    name: "Desert",
    item: [
      { name: "Fried Desert", url: "fried.jpg" },
      { name: "Cake", url: "cake.jpg" },
      { name: "Gelatin", url: "gelatin.jpg" },
      { name: "Pastry", url: "pastry.jpg" },
      { name: "Ice Cream", url: "ice-cream.jpg" },
      { name: "Pie", url: "pie.jpg" },
      { name: "Pudding", url: "pudding.jpg" },
      { name: "Cupcake", url: "cupcake.jpg" },
      { name: "Ice Cream Cake", url: "ice-cream-cake.jpg" },
      { name: "Brownie", url: "brownie.jpg" },
    ],
  },
  {
    name: "Mexican",
    item: [
      { name: "Tacos", url: "tacos.jpg" },
      { name: "Dorilocos", url: "dorilocos.jpg" },
      { name: "Birria", url: "birria.jpg" },
      { name: "Refried Bean Salad", url: "refried-bean-salad.jpg" },
      { name: "Mexican Rice", url: "mexican-rice.jpg" },
      { name: "Calabacitas", url: "calabacitas.jpg" },
      { name: "Chicken Fajita", url: "chicken-fajita.jpg" },
      { name: "Pozole", url: "pozole.jpg" },
      { name: "Enchiladas", url: "enchiladas.jpg" },
      { name: "Guacamole", url: "guacamole.jpg" },
    ],
  },
  {
    name: "French",
    item: [
      { name: "Crème brûlée", url: "creme.jpg" },
      { name: "Salade niçoise", url: "salade.jpg" },
      { name: "Foie Gras", url: "foie.jpg" },
      { name: "Soufflé", url: "souffle.jpg" },
      { name: "Escargots", url: "escargots.jpg" },
      { name: "Tartiflette", url: "tartiflette.jpg" },
      { name: "Steak Tartare", url: "steak.jpg" },
      { name: "Cassoulet", url: "cassoulet.jpg" },
      { name: "Blanquette de Veau", url: "blanquette.jpg" },
      { name: "Pissaladière", url: "pissaladiere.jpg" },
    ],
  },
  {
    name: "Indian",
    item: [
      { name: "Chicken Makhani", url: "chicken.jpg" },
      { name: "Tandori Chicken", url: "tandori-chicken.jpg" },
      { name: "Idli Dosa", url: "idli.jpg" },
      { name: "Hyderabad Biriyani", url: "biriyani.jpg" },
      { name: "Aloo gobi", url: "gobi.jpg" },
      { name: "Matar Paneer", url: "matar-paneer.jpg" },
      { name: "Chana Aloo Curry", url: "chana.jpg" },
      { name: "Jeera Rice", url: "jeera.jpg" },
      { name: "Fish Curry", url: "fish.jpg" },
      { name: "Aloo Paratha", url: "aloo.jpg" },
    ],
  },
];
